### PR TITLE
GHC-8.4.1 is not alpha anymore

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
Blocked on https://github.com/ChrisKuklewicz/regex-tdfa/pull/16, that cannot be worked around by `allow-newer`. I'd like to run tests with `ghc-8.4.1` before the release.

cc @varosi: we previously used `head.hackage` overlay, but for proper release I'd like to build from Hackage proper.

**Comment by varosi** [comment]
Okay, thanks!

**Comment by cocreature** [comment]
Why is this blocked on `regex-tdfa`? Shouldn’t a test with `tasty >= 1.0` (which doesn’t depend on `regex-tdfa`) be sufficient?

**Comment by phadej** [comment]
Good point. I'll bump test dependencies bounds tomorrow (Wed) and rerun the checks.

**Comment by phadej** [comment]
https://hackage.haskell.org/package/integer-logarithms-1.0.2.1

**Comment by cocreature** [comment]
Thanks!

**Comment by cocreature** [comment]
Thanks!

**Pull request merged**
