### PR TITLE
Support GHC 8.8

### PR DESCRIPTION
**Pull request by fumieval**
Pardon an automatically-posted pull request; this is a part of [Operation Vanguard](https://github.com/haskell-vanguard/haskell-vanguard). Note that this does not guarantee that tests and benchmarks are buildable.

### CODE REVIEW

**Comment by Bodigrim** [comment]
@fumieval could you please enlighten me about goals of Operation Vanguard? What makes it different from adding patches to https://github.com/hvr/head.hackage?

**Comment by fumieval** [comment]
As far as I understand, head.hackage does not do anything to the upstream repositories. I wanted to help folks who happened to have to use code on GitHub, as well as making repos in sync with Hackage.

**Comment by Bodigrim** [comment]
Thanks for contribution, but I feel no urgency to release it until GHC 8.8 is cut. In the meantime one can use `--allow-newer`. 

It does not seem likely that any additional changes will be needed for the upcoming GHC release, but in general `integer-logarithms` has too many downstream dependencies and we'd rather do not mess with releases/revisions before time, especially when a simple and cheap workaround is available.

**Comment by Bodigrim** [comment]
I mean, it totally makes sense to merge source code's patches (but none are needed), but we cannot yet proclaim that `base-4.13` is supported (basically, because there is no `base-4.13` released).

**Comment by phadej** [comment]
As there is [GHC-8.8.1-rc1](https://www.haskell.org/ghc/blog/20190722-ghc-8.8.1-rc1-released.html) I made [a revision](https://hackage.haskell.org/package/integer-logarithms-1.0.3/revisions/) to allow base-4.13 (see https://github.com/Bodigrim/integer-logarithms/pull/23)

**Pull request closed without merging**
